### ISSUE TITLE
TODO!:

### ISSUE THREAD

**Issue by DivachiLeonerd** [DivachiLeonerd/Minishell_V2#5]
In makefile the creation of obj files is considered "intermediate" and , therefore, deleted. Needs changing by putting the creation of obj files as a recipe or a prerequisite.

**Comment by DivachiLeonerd** [comment]
- [ ]  Put specific recipes to convert c files into object files. MAKE SURE THEY ARE ALL COMPILING WITH FLAGS
- [ ]  object recipe should have the C files as prerequisites so that if there is a change in one of them they recompile
- [ ] Be careful with re-linking

**Comment by DivachiLeonerd** [comment]
- [ ] finish str_expander.c according to the rules in the comments.
